#!/usr/bin/env sh

set -eu

USERS="plietar M-Kusumgar richfitz weshinsley EmmaLRussell david-mears-2"
OUTPUT=authorized_keys

echo "# Do not edit! This was generated by scripts/update-ssh-keys.sh" > $OUTPUT

for username in $USERS; do
  echo "Fetching keys for $username"
  curl -sS --fail "https://github.com/$username.keys" | awk "{print \$0, \"$username\"}" >> $OUTPUT
done
