#!/usr/bin/env sh

USERS="plietar M-Kusumgar richfitz weshinley"
OUTPUT=authorized_keys

echo "# Do not edit! This was generated by scripts/update-ssh-keys.sh" > $OUTPUT

for username in $USERS; do
  curl -sS "https://github.com/$username.keys" >> $OUTPUT
done
